<!--
  @component
  Renders an image generated by Slop Machine.

  This component automatically constructs the correct URL for the Slop Machine API,
  displays a loading skeleton or custom loader while fetching, and handles errors.

  @example
  ```svelte
  <SlopImage
    bucketId="my-bucket"
    resultId="some-result"
    aspectRatio="16:9"
    class="rounded-lg"
  />
  ```

  @version 0.9.0
-->
<script lang="ts">
  import {
    buildImageUrl,
    createRenderUrlMonitor,
    type SlopMachineError,
    type SlopImageOptions,
    type ImageAspectRatio,
  } from "@slopmachine/core";
  import { untrack, type Snippet } from "svelte";
  import ErrorOverlay from "./ErrorOverlay.svelte";

  export interface SlopImageProps extends Omit<
    SlopImageOptions,
    "aspectRatio"
  > {
    /**
     * The aspect ratio of the generated image. Defaults to "1:1".
     */
    aspectRatio?: ImageAspectRatio;
    /**
     * Alternative text describing the image, for screen readers and when the image
     * can't be shown. Defaults to "Image produced by Slop Machine (slopmachine.dev)".
     * Describe what the image shows, or pass `""` if it's purely decorative.
     */
    alt?: string;
    /**
     * Additional CSS classes to apply to the wrapper element.
     */
    class?: string;
    /**
     * Custom Svelte snippet to display while the image is loading.
     * If not provided, a default spinner and shimmer effect will be shown.
     */
    loader?: Snippet;
    /**
     * Custom Svelte snippet to display if the image fails to generate or load.
     * Receives `{ error }`, a `SlopMachineError`.
     * If not provided, a default error message is shown in place of the image.
     */
    errorFallback?: Snippet<[{ error: SlopMachineError }]>;
    /**
     * Called once per URL when the image fails to generate or load.
     * `error.status` holds the HTTP status when the API reported the failure.
     */
    onGenerationError?: (error: SlopMachineError) => void;
    /**
     * How the image should be resized to fit its container. Defaults to "cover".
     */
    objectFit?: "fill" | "contain" | "cover" | "none" | "scale-down";
    /**
     * Additional CSS classes to apply directly to the `<img />` element.
     */
    imageClass?: string;
    [key: string]: any;
  }

  let {
    bucketId = undefined,
    pipelineId = undefined,
    siloId = undefined,
    prompt = undefined,
    metadata = undefined,
    aspectRatio = "1:1",
    alt = "Image produced by Slop Machine (slopmachine.dev)",
    model = undefined,
    version = undefined,
    resultId = undefined,
    variables = {},
    baseUrl = undefined,
    original = false,
    attachments = undefined,
    class: className = "",
    objectFit = "cover",
    imageClass = "",
    loader,
    errorFallback,
    onGenerationError,
    onload,
    onerror,
    ...restProps
  }: SlopImageProps = $props();

  let isLoading = $state(true);
  let error = $state<SlopMachineError | null>(null);

  let computedSrc = $derived(
    buildImageUrl({
      bucketId,
      pipelineId,
      siloId,
      prompt,
      metadata,
      aspectRatio,
      model,
      version,
      resultId,
      variables,
      baseUrl,
      original,
      attachments,
    }),
  );
  // Use the URL straight away (also when server-rendering); only later changes are debounced
  let src = $state(untrack(() => computedSrc));
  let prevSrc = $state(untrack(() => computedSrc));

  $effect(() => {
    // Debounce rapid prop changes (same delay as the React components)
    const currentComputedSrc = computedSrc;
    const timeout = setTimeout(() => {
      if (src !== currentComputedSrc) {
        src = currentComputedSrc;
      }
    }, 100);

    return () => clearTimeout(timeout);
  });

  $effect(() => {
    if (src !== prevSrc) {
      isLoading = true;
      error = null;
      prevSrc = src;
    }
  });

  // Shares one URL check between the HEAD probe and the media element's error event
  const monitor = createRenderUrlMonitor((err) => {
    console.error("SlopImage error:", err.status ?? "", err.message);
    isLoading = false;
    error = err;
    onGenerationError?.(err);
  });

  $effect(() => {
    if (!src) return;
    monitor.watch(src);
    return () => monitor.stop();
  });

  function handleLoad(e: Event) {
    isLoading = false;
    onload?.(e);
  }

  function handleError(e: Event) {
    // An empty src (before the debounced URL is set) can fire a spurious error
    if (src) monitor.mediaFailed(src, "Failed to load image");
    onerror?.(e);
  }
</script>

<div class={className}>
  <div
    class="slop-wrapper"
    style="aspect-ratio: {aspectRatio?.replace(':', '/')};"
  >
    {#if isLoading}
      {#if loader}
        <div class="custom-loader-wrapper">
          {@render loader()}
        </div>
      {:else}
        <div class="loading-overlay">
          <div class="spinner-container">
            <svg
              class="spinner"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                stroke-width="4"
              ></circle>
              <path
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              ></path>
            </svg>
            <span>Loading...</span>
          </div>
        </div>
        <div class="shimmer-effect"></div>
      {/if}
    {/if}

    {#if error}
      <ErrorOverlay {error} {errorFallback} label="Failed to load image" />
    {/if}

    <img
      src={src || undefined}
      {alt}
      style="object-fit: {objectFit};"
      class="slop-image {imageClass} {isLoading || error ? '' : 'loaded'}"
      {...restProps}
      aria-hidden={error ? true : restProps["aria-hidden"]}
      onload={handleLoad}
      onerror={handleError}
    />
  </div>
</div>

<style>
  .slop-wrapper {
    position: relative;
    overflow: hidden;
    width: 100%;
    height: 100%;
  }

  .loading-overlay,
  .custom-loader-wrapper {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: opacity 300ms ease-in-out;
  }

  .loading-overlay {
    background-color: var(--slop-muted, var(--muted, #f3f4f6));
  }

  .spinner-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
  }

  .spinner {
    width: 24px;
    height: 24px;
    color: var(--slop-muted-foreground, var(--muted-foreground, #6b7280));
    animation: slop-spin 1s linear infinite;
  }
  .spinner circle {
    opacity: 0.25;
  }
  .spinner path {
    opacity: 0.75;
  }

  .spinner-container span {
    font-size: 0.75rem;
    color: var(--slop-muted-foreground, var(--muted-foreground, #6b7280));
  }

  .shimmer-effect {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(
      90deg,
      var(--slop-muted, var(--muted, #f3f4f6)) 0%,
      var(--slop-shimmer, var(--muted-foreground, #e5e7eb)) 50%,
      var(--slop-muted, var(--muted, #f3f4f6)) 100%
    );
    background-size: 200% 100%;
    animation: slop-shimmer 2s ease-in-out infinite;
  }

  .slop-image {
    height: 100%;
    width: 100%;
    transition: opacity 500ms;
    opacity: 0;
  }

  .slop-image.loaded {
    opacity: 1;
  }

  @keyframes slop-shimmer {
    0% {
      background-position: 200% 0;
    }
    100% {
      background-position: -200% 0;
    }
  }

  @keyframes slop-spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
</style>
