<!--
  @component
  Renders text generated by Slop Machine.

  This component automatically constructs the correct URL for the Slop Machine API,
  fetches the generated text, and renders it as sanitized Markdown, with optional
  loading and error states.

  @example
  ```svelte
  <SlopText bucketId="my-text-bucket" class="text-lg text-gray-800">
    {#snippet fallback()}
      <div>Loading story...</div>
    {/snippet}
    {#snippet errorFallback({ error })}
      <div>Failed to load story: {error.message}</div>
    {/snippet}
  </SlopText>
  ```

  @version 0.8.1
-->
<script lang="ts">
  import {
    buildTextUrl,
    fetchRenderedText,
    renderMarkdown,
    SlopMachineError,
    type SlopTextOptions,
  } from "@slopmachine/core";
  import type { Snippet } from "svelte";
  import ErrorOverlay from "./ErrorOverlay.svelte";

  export interface SlopTextProps extends SlopTextOptions {
    /**
     * Custom Svelte snippet to display while the text is loading.
     * If not provided, a default spinner and shimmer effect will be shown.
     */
    fallback?: Snippet;
    /**
     * Custom Svelte snippet to display if the text fails to generate or load.
     * Receives `{ error }`, a `SlopMachineError`.
     * If not provided, a default error message is shown.
     */
    errorFallback?: Snippet<[{ error: SlopMachineError }]>;
    /**
     * Called once per URL when the text fails to generate or load.
     * `error.status` holds the HTTP status when the API reported the failure.
     */
    onGenerationError?: (error: SlopMachineError) => void;
    /**
     * Additional CSS classes to apply to the wrapper element.
     */
    class?: string;
    /**
     * Inline styles to apply to the wrapper element.
     */
    style?: string;
    [key: string]: any;
  }

  let {
    bucketId = undefined,
    pipelineId = undefined,
    siloId = undefined,
    prompt = undefined,
    metadata = undefined,
    version = undefined,
    resultId = undefined,
    model = undefined,
    variables = undefined,
    baseUrl = undefined,
    attachments = undefined,
    errorFallback,
    fallback,
    onGenerationError,
    class: className = "",
    style = "",
    ...rest
  }: SlopTextProps = $props();

  let text: string | null = $state(null);
  let loading = $state(true);
  let error: SlopMachineError | null = $state(null);

  let url = $derived(
    buildTextUrl({
      bucketId,
      pipelineId,
      siloId,
      prompt,
      metadata,
      version,
      resultId,
      model,
      variables,
      baseUrl,
      attachments,
    }),
  );

  $effect(() => {
    // Cancels the request if the URL changes or the component unmounts,
    // so a slow response for an old URL can never replace newer text
    const controller = new AbortController();
    loading = true;
    error = null;

    fetchRenderedText(url, { signal: controller.signal })
      .then((content) => {
        text = content;
        loading = false;
      })
      .catch((err) => {
        if (controller.signal.aborted) return;
        const finalError =
          err instanceof SlopMachineError
            ? err
            : new SlopMachineError("Failed to load text");
        console.error(
          "SlopText error:",
          finalError.status ?? "",
          finalError.message,
        );
        error = finalError;
        loading = false;
        onGenerationError?.(finalError);
      });

    return () => controller.abort();
  });
</script>

{#if error}
  {#if errorFallback}
    {@render errorFallback({ error })}
  {:else}
    <div class={className} {style} {...rest}>
      <div class="slop-wrapper">
        <ErrorOverlay {error} label="Failed to load text" />
      </div>
    </div>
  {/if}
{:else if loading}
  {#if fallback}
    {@render fallback()}
  {:else}
    <div class={className} {style}>
      <div class="slop-wrapper">
        <div class="loading-overlay">
          <div class="spinner-container">
            <svg
              class="spinner"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                stroke-width="4"
              ></circle>
              <path
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              ></path>
            </svg>
            <span>Loading...</span>
          </div>
        </div>
        <div class="shimmer-effect"></div>
      </div>
    </div>
  {/if}
{:else}
  <div class={className} {style} {...rest}>
    {@html text ? renderMarkdown(text) : ""}
  </div>
{/if}

<style>
  .slop-wrapper {
    position: relative;
    overflow: hidden;
    width: 100%;
    min-height: 100px;
  }

  .loading-overlay {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: var(--slop-muted, var(--muted, #f3f4f6));
  }

  .spinner-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
  }

  .spinner {
    width: 24px;
    height: 24px;
    color: var(--slop-muted-foreground, var(--muted-foreground, #6b7280));
    animation: slop-spin 1s linear infinite;
  }
  .spinner circle {
    opacity: 0.25;
  }
  .spinner path {
    opacity: 0.75;
  }

  .spinner-container span {
    font-size: 0.75rem;
    color: var(--slop-muted-foreground, var(--muted-foreground, #6b7280));
  }

  .shimmer-effect {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(
      90deg,
      var(--slop-muted, var(--muted, #f3f4f6)) 0%,
      var(--slop-shimmer, var(--muted-foreground, #e5e7eb)) 50%,
      var(--slop-muted, var(--muted, #f3f4f6)) 100%
    );
    background-size: 200% 100%;
    animation: slop-shimmer 2s ease-in-out infinite;
  }

  @keyframes slop-shimmer {
    0% {
      background-position: 200% 0;
    }
    100% {
      background-position: -200% 0;
    }
  }

  @keyframes slop-spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
</style>
