import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  buildTextUrl,
  fetchRenderedText,
  renderMarkdown,
  SlopMachineError,
  type SlopTextOptions,
} from "@slopmachine/core";
import { ErrorOverlay, type SlopErrorFallback } from "./ErrorOverlay";

export interface SlopTextProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "children">,
    SlopTextOptions {
  /**
   * Optional loading component to show while the text is being generated.
   * If not provided, a default spinner and shimmer effect will be shown.
   */
  fallback?: React.ReactNode;
  /**
   * Content to display if the text fails to generate or load.
   * Pass a node, or a function that receives the `SlopMachineError` and returns a node.
   * If not provided, a default error message is shown.
   */
  errorFallback?: SlopErrorFallback;
  /**
   * Called once per URL when the text fails to generate or load.
   * `error.status` holds the HTTP status when the API reported the failure.
   */
  onGenerationError?: (error: SlopMachineError) => void;
}

/**
 * Renders text generated by Slop Machine.
 *
 * This component automatically constructs the correct URL for the Slop Machine API,
 * fetches the generated text, and displays it with optional loading and error states.
 *
 * @example
 * ```tsx
 * // Using a Bucket
 * <SlopText
 *   bucketId="my-text-bucket"
 *   fallback={<div>Loading story...</div>}
 *   errorFallback={(error) => <div>Failed to load story: {error.message}</div>}
 *   className="text-lg text-gray-800"
 * />
 *
 * // Using a Pipeline with runtime prompt
 * <SlopText
 *   pipelineId="pipe_live_abc123"
 *   prompt="Write a whimsical haiku about quantum physics"
 *   metadata={{ userId: "123" }}
 * />
 * ```
 *
 * @version 0.8.1
 */
export const SlopText = React.forwardRef<HTMLDivElement, SlopTextProps>(
  (
    {
      bucketId,
      pipelineId,
      siloId,
      prompt,
      metadata,
      version,
      resultId,
      model,
      variables,
      baseUrl,
      attachments,
      fallback,
      errorFallback,
      onGenerationError,
      ...props
    },
    ref,
  ) => {
    const [text, setText] = useState<string | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<SlopMachineError | null>(null);

    const rawUrl = useMemo(
      () =>
        buildTextUrl({
          bucketId,
          pipelineId,
          siloId,
          prompt,
          metadata,
          version,
          resultId,
          model,
          variables,
          baseUrl,
          attachments,
        }),
      [
        bucketId,
        pipelineId,
        siloId,
        prompt,
        JSON.stringify(metadata),
        version,
        resultId,
        model,
        JSON.stringify(variables),
        baseUrl,
        JSON.stringify(attachments),
      ],
    );

    // Keep the latest callback without re-running the fetch when it changes identity
    const onGenerationErrorRef = useRef(onGenerationError);
    useEffect(() => {
      onGenerationErrorRef.current = onGenerationError;
    });

    useEffect(() => {
      // Cancels the request if the URL changes or the component unmounts,
      // so a slow response for an old URL can never replace newer text
      const controller = new AbortController();
      setLoading(true);
      setError(null);

      fetchRenderedText(rawUrl, { signal: controller.signal })
        .then((content) => {
          setText(content);
          setLoading(false);
        })
        .catch((err) => {
          if (controller.signal.aborted) return;
          const finalError =
            err instanceof SlopMachineError
              ? err
              : new SlopMachineError("Failed to load text");
          console.error(
            "SlopText error:",
            finalError.status ?? "",
            finalError.message,
          );
          setError(finalError);
          setLoading(false);
          onGenerationErrorRef.current?.(finalError);
        });

      return () => controller.abort();
    }, [rawUrl]);

    if (error) {
      if (errorFallback !== undefined) {
        return (
          <>
            {typeof errorFallback === "function"
              ? errorFallback(error)
              : errorFallback}
          </>
        );
      }
      return (
        <div ref={ref} {...props}>
          <div
            className="slop-wrapper relative overflow-hidden w-full"
            style={{
              position: "relative",
              overflow: "hidden",
              width: "100%",
              minHeight: "100px",
            }}
          >
            <ErrorOverlay error={error} label="Failed to load text" />
          </div>
        </div>
      );
    }

    if (loading) {
      if (fallback) {
        return <>{fallback}</>;
      }
      return (
        <div className={props.className} style={props.style}>
          <style>{`
            @keyframes slop-shimmer {
              0% { background-position: 200% 0; }
              100% { background-position: -200% 0; }
            }
            @keyframes slop-spin {
              from { transform: rotate(0deg); }
              to { transform: rotate(360deg); }
            }
          `}</style>
          <div
            className="slop-wrapper relative overflow-hidden w-full"
            style={{
              position: "relative",
              overflow: "hidden",
              width: "100%",
              minHeight: "100px",
            }}
          >
            {/* Loading overlay */}
            <div
              className="absolute inset-0 z-10 flex items-center justify-center bg-muted transition-opacity duration-300"
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                zIndex: 10,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                backgroundColor: "var(--slop-muted, var(--muted, #f3f4f6))",
              }}
            >
              <div
                className="flex flex-col items-center gap-2"
                style={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  gap: "0.5rem",
                }}
              >
                <svg
                  className="spinner size-6 text-muted-foreground"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  style={{
                    width: "24px",
                    height: "24px",
                    color:
                      "var(--slop-muted-foreground, var(--muted-foreground, #6b7280))",
                    animation: "slop-spin 1s linear infinite",
                  }}
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                    style={{ opacity: 0.25 }}
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    style={{ opacity: 0.75 }}
                  />
                </svg>
                <span
                  className="text-xs text-muted-foreground"
                  style={{
                    fontSize: "0.75rem",
                    color:
                      "var(--slop-muted-foreground, var(--muted-foreground, #6b7280))",
                  }}
                >
                  Loading...
                </span>
              </div>
            </div>

            {/* Shimmer effect underneath */}
            <div
              className="shimmer-effect absolute inset-0 bg-gradient-to-r from-muted via-muted/50 to-muted"
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                background:
                  "linear-gradient(90deg, var(--slop-muted, var(--muted, #f3f4f6)) 0%, var(--slop-shimmer, var(--muted-foreground, #e5e7eb)) 50%, var(--slop-muted, var(--muted, #f3f4f6)) 100%)",
                backgroundSize: "200% 100%",
                animation: "slop-shimmer 2s ease-in-out infinite",
              }}
            />
          </div>
        </div>
      );
    }

    return (
      <div
        ref={ref}
        {...props}
        dangerouslySetInnerHTML={{
          __html: text ? renderMarkdown(text) : "",
        }}
      />
    );
  },
);

SlopText.displayName = "SlopText";
